application: getirkit
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

# ignore app.go, we use it to `go run app.go`
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^app\.go$
